server:
  port: 8801

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:9999/eureka/"

spring:
  application:
    name: "user-service"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.4.28:5432/pacsdb
    username: pacs
    password: pacs

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    joda-date-time-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"


mybatis:
  mapper-locations: classpath:mappers/*.xml


dcm4chee:
  host: http://ct.intellifai.cn:9000