server:
  port: 9999

eureka:
  server:
    enable-self-preservation: false  #开发环境时，来关闭保护机制，以确保注册中心可以不将不可用的实例正确剔除

  instance:
    hostname: "eureka-server"
  client:
    healthcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring.cloud.config.discovery.enabled: true